### ISSUE TITLE
Would you mind adding a licence?

### ISSUE THREAD

**Issue by nvnnghia** [ufownl/global-wheat-detection#1]
Hi @ufownl ,
Thanks for sharing your great works. I would like to add a model using your script into our ensemble pipeline. Would you mind adding a licence for your repo, so that I can use it? Thank you very much.

Regards,
Nya

**Comment by ufownl** [comment]
Hi @nvnnghia , Apache-2.0 License has been added to this repo.

**Comment by nvnnghia** [comment]
Thanks @ufownl
